# Generated by Django 4.2.15 on 2024-09-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AddField(
            model_name='answer',
            name='filled_cells',
            field=models.JSONField(blank=True, null=True, verbose_name='Заполненные ячейки'),
        ),
        migrations.AddField(
            model_name='answer',
            name='reordered_items',
            field=models.JSONField(blank=True, null=True, verbose_name='Переставленные элементы'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовое поле'), ('table', 'Таблица'), ('reorder', 'Перестановка')], default=1, max_length=50, verbose_name='Тип вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ'),
        ),
    ]
