# Generated by Django 4.2.15 on 2024-11-12 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lesson_presentation_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_alter_answer_options_question_check_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ')),
                ('placeholder', models.TextField(blank=True, null=True, verbose_name='Подсказка для ввода ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='MultyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название теста')),
                ('answers', models.ManyToManyField(blank=True, to='quiz.multyanswer', verbose_name='Ответы')),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multy_tests', to='main.lesson')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовое поле')], max_length=50, verbose_name='Сұрақ түрі'),
        ),
        migrations.CreateModel(
            name='StudentTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(blank=True, null=True, verbose_name='Ответы студента')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.multytest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Ответ студента на тест',
                'verbose_name_plural': 'Ответы студентов на тесты',
            },
        ),
    ]
