# Generated by Django 4.2.15 on 2024-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_multyanswer_multytest_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multyanswer',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='multyanswer',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка для ввода ответа'),
        ),
    ]
