# Generated by Django 4.2.15 on 2024-11-12 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_alter_multyanswer_name_alter_multyanswer_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Тест-курс',
                'verbose_name_plural': 'Тесты-курсы',
            },
        ),
        migrations.AlterField(
            model_name='multytest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название вопроса: '),
        ),
        migrations.AlterUniqueTogether(
            name='studenttestresponse',
            unique_together={('student', 'test')},
        ),
        migrations.AddIndex(
            model_name='studenttestresponse',
            index=models.Index(fields=['student', 'test'], name='quiz_studen_student_203d1b_idx'),
        ),
        migrations.AddField(
            model_name='tests',
            name='tests',
            field=models.ManyToManyField(blank=True, to='quiz.multytest', verbose_name='Тесты'),
        ),
    ]
