# Generated by Django 4.2.15 on 2024-11-12 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_tests_alter_multytest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, null=True, verbose_name='Текстовый ответ')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('multy_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.multytest', verbose_name='Вопрос')),
                ('selected_answers', models.ManyToManyField(blank=True, to='quiz.multyanswer', verbose_name='Выбранные ответы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.tests', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Ответ на тест',
                'verbose_name_plural': 'Ответы на тесты',
                'indexes': [models.Index(fields=['student', 'test', 'multy_test'], name='quiz_testre_student_0379a9_idx')],
                'unique_together': {('student', 'test', 'multy_test')},
            },
        ),
    ]
