# Generated by Django 4.2.15 on 2024-11-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_testresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresponse',
            name='response_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Ответы в формате JSON'),
        ),
    ]
