# Generated by Django 4.2.15 on 2025-01-10 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_testresponse2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multyanswer',
            options={'verbose_name': 'Ответ - 2', 'verbose_name_plural': 'Ответы - 2'},
        ),
        migrations.AlterModelOptions(
            name='multytest',
            options={'verbose_name': 'Вопрос - 2', 'verbose_name_plural': 'Вопросы -2'},
        ),
        migrations.AlterModelOptions(
            name='testresponse2',
            options={'verbose_name': 'Ответ на тест -2', 'verbose_name_plural': 'Ответы на тесты -2'},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name': 'Тест-курс - 2', 'verbose_name_plural': 'Тесты-курсы - 2'},
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Пайдаланушы тест үшін жинаған ұпайлар.', verbose_name='Бағасы')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quiz.tests', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланушы')),
            ],
            options={
                'verbose_name': 'Бағасы',
                'verbose_name_plural': 'Бағасы',
            },
        ),
    ]
