# Generated by Django 4.2.15 on 2024-09-21 07:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Туған күн: '),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон нөмірі: '),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Толық сипаттама:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(verbose_name='Дәріс нөмірі'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Қысқаша сипаттама:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Дәрістің атауы:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Сілтеме:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='presentation',
            field=models.CharField(max_length=200, verbose_name='PowerPoint бағдарламасындағы тапсырма:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Сілтеме:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='word',
            field=models.CharField(max_length=200, verbose_name='Word бағдарламасындағы тапсырма:'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Сабақтың атауы:'),
        ),
    ]
