# Generated by Django 4.2.15 on 2024-08-25 11:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Краткое описание:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудио:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полное описание:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(verbose_name='Номер лекции'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название лекции:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Ссылка:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео:'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название урока:'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото:'),
        ),
    ]
