# Generated by Django 4.2.15 on 2024-10-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='presentation_url',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default='/embed', null=True, verbose_name='Видеоға сілтеме'),
        ),
    ]
