# Generated by Django 4.2.15 on 2024-10-15 15:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lesson_presentation_url_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Әкесінің аты: '),
        ),
        migrations.AddField(
            model_name='lesson',
            name='glossary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Глоссарий:'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Бақылау сұрақтары:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presentation_url',
            field=models.URLField(blank=True, null=True, verbose_name='Презентацияға сілтеме'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default='/embed/', null=True, verbose_name='Видеоға сілтеме'),
        ),
    ]
