# Generated by Django 4.2.15 on 2024-10-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_middle_name_lesson_glossary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='presentation_urls',
            field=models.URLField(blank=True, null=True, verbose_name='Презентацияға сілтеме 2 '),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presentation_url',
            field=models.URLField(blank=True, null=True, verbose_name='Презентацияға сілтеме 1 '),
        ),
    ]
