# Generated by Django 4.2.15 on 2024-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lesson_presentation_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='presentation_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Презентацияға сілтеме 1'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presentation_urls',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Презентацияға сілтеме 2'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/g-XlulPAV8E', null=True, verbose_name='Видеоға сілтеме'),
        ),
    ]
