# Generated by Django 4.2.15 on 2024-09-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Жауап', 'verbose_name_plural': 'Жауаптар'},
        ),
        migrations.AlterModelOptions(
            name='studentsubmission',
            options={'verbose_name': 'Студенттердің жауабы', 'verbose_name_plural': 'Студенттердің жауабы'},
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии к оценке'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка'),
        ),
    ]
