# Generated by Django 4.2.15 on 2024-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_question_answer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовое поле')], default='1', max_length=20, verbose_name='Сұрақ түрі'),
        ),
    ]
