# Generated by Django 4.2.15 on 2024-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
